# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine as builder

WORKDIR /app

# Install dependencies for the mcp server
COPY browser-tools-mcp/package*.json ./browser-tools-mcp/
RUN cd browser-tools-mcp && npm install --ignore-scripts

# Copy the rest of the source code
COPY browser-tools-mcp ./browser-tools-mcp

# Build the TypeScript code
RUN cd browser-tools-mcp && npx tsc

FROM node:lts-alpine
WORKDIR /app

# Copy built files from the builder stage
COPY --from=builder /app/browser-tools-mcp ./browser-tools-mcp

# Expose port if required by the MCP server (optional)
# EXPOSE 3025

# Run the MCP server
CMD ["node", "browser-tools-mcp/dist/mcp-server.js"]
